use rand::Rng;

const LOWERCASE: &[u8] = b"abcdefghijklmnopqrstuvwxyz";
const UPPERCASE: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const DIGITS: &[u8] = b"0123456789";
const SYMBOLS: &[u8] = b"!@#$%^&*()-_=+[]{}|;:,.<>?";

const WORDLIST: &[&str] = &[
    "abandon", "ability", "able", "about", "above", "absent", "absorb", "abstract",
    "absurd", "abuse", "access", "acid", "acoustic", "acquire", "across", "action",
    "actor", "address", "adjust", "admit", "adult", "advance", "advice", "aerobic",
    "afford", "afraid", "again", "agent", "agree", "ahead", "aim", "air",
    "airport", "aisle", "alarm", "album", "alcohol", "alert", "alien", "almost",
    "alone", "alpha", "already", "also", "alter", "always", "amateur", "amazing",
    "among", "amount", "amused", "anchor", "ancient", "anger", "angle", "angry",
    "animal", "ankle", "announce", "annual", "another", "answer", "antenna", "antique",
    "anxiety", "apart", "apology", "appear", "apple", "approve", "arena", "argue",
    "armor", "army", "arrest", "arrive", "arrow", "artist", "asthma", "atom",
    "attack", "attend", "attract", "auction", "audit", "august", "aunt", "autumn",
    "average", "avocado", "avoid", "awake", "aware", "awesome", "awful", "awkward",
    "banana", "banner", "bargain", "barrel", "basket", "battle", "beach", "bean",
    "beauty", "become", "before", "begin", "behave", "believe", "bench", "benefit",
    "best", "betray", "beyond", "bicycle", "bitter", "blanket", "bless", "blind",
    "blood", "blossom", "board", "bonus", "bottom", "bounce", "brave", "bread",
    "breeze", "brick", "bridge", "bright", "bring", "broken", "brother", "brown",
    "brush", "bubble", "buddy", "budget", "buffalo", "build", "burden", "burger",
    "butter", "cabin", "cable", "cactus", "camera", "camp", "canal", "cancel",
    "canvas", "canyon", "capable", "captain", "carbon", "cargo", "carpet", "carry",
    "castle", "catalog", "catch", "cattle", "caught", "cause", "caution", "cave",
    "celery", "cement", "census", "century", "cereal", "certain", "chair", "change",
    "chapter", "charge", "cherry", "chicken", "chief", "child", "chimney", "choice",
    "chunk", "circle", "citizen", "claim", "clap", "clarify", "claw", "clean",
    "clever", "cliff", "climb", "clinic", "clip", "clock", "close", "cloth",
    "cloud", "cluster", "coach", "coconut", "coffee", "collect", "color", "column",
    "combine", "comfort", "comic", "common", "company", "concert", "conduct", "confirm",
    "connect", "consider", "control", "convince", "copper", "coral", "corner", "correct",
    "cotton", "couch", "country", "couple", "course", "cousin", "cover", "craft",
    "crane", "crash", "crater", "cream", "credit", "creek", "crew", "cricket",
    "crime", "crisp", "cruel", "cruise", "crumble", "crush", "crystal", "cube",
    "culture", "curtain", "curve", "cushion", "custom", "cycle", "damage", "dance",
    "danger", "daring", "daughter", "dawn", "debate", "debris", "decade", "december",
    "decide", "defense", "define", "degree", "delay", "demand", "denial", "dentist",
    "depart", "depend", "deposit", "depth", "deputy", "derive", "desert", "design",
    "detail", "detect", "develop", "device", "devote", "diamond", "diary", "diesel",
    "differ", "digital", "dignity", "dilemma", "dinner", "dinosaur", "direct", "disease",
    "dismiss", "display", "distance", "divert", "document", "dolphin", "domain", "donate",
    "donkey", "donor", "double", "dove", "draft", "dragon", "drama", "dress",
    "drift", "drink", "drip", "drive", "drum", "dry", "duck", "dumb",
    "dune", "during", "dust", "dutch", "dwarf", "dynamic", "eager", "eagle",
    "earth", "easily", "ecology", "economy", "edge", "effort", "eight", "either",
    "elbow", "elder", "electric", "elegant", "element", "elephant", "elevator", "elite",
    "embrace", "emerge", "emotion", "employ", "empower", "enable", "endorse", "enemy",
    "energy", "enforce", "engage", "engine", "enhance", "enjoy", "enough", "enrich",
    "ensure", "enter", "entire", "entry", "envelope", "episode", "equal", "equip",
    "erode", "erosion", "error", "escape", "essay", "essence", "estate", "eternal",
    "evidence", "evil", "evolve", "exact", "example", "excess", "exchange", "excite",
    "exclude", "excuse", "execute", "exhaust", "exhibit", "exile", "expand", "expect",
    "expire", "explain", "expose", "express", "extend", "extra", "eyebrow", "fabric",
    "faculty", "faint", "faith", "fall", "famous", "fancy", "fantasy", "fashion",
    "father", "fault", "favorite", "feature", "february", "federal", "fence", "festival",
    "fetch", "fever", "fiction", "field", "figure", "filter", "final", "finger",
    "finish", "fire", "firm", "fiscal", "fitness", "flag", "flame", "flash",
    "flavor", "flight", "flip", "float", "flock", "floor", "flower", "fluid",
    "focus", "follow", "food", "force", "forest", "forget", "fork", "fortune",
    "fossil", "foster", "found", "fragile", "frame", "frequent", "fresh", "friend",
    "fringe", "frog", "frozen", "fruit", "funny", "furnace", "fury", "future",
    "gadget", "galaxy", "gallery", "game", "garage", "garbage", "garden", "garlic",
    "gather", "gauge", "general", "genius", "genre", "gentle", "genuine", "gesture",
    "ghost", "giant", "gift", "giggle", "ginger", "giraffe", "glance", "glare",
    "glass", "globe", "gloom", "glory", "glove", "glow", "glue", "goat",
    "goddess", "gold", "gospel", "gossip", "govern", "grace", "grain", "gravity",
    "great", "green", "grid", "grief", "grocery", "group", "grow", "grunt",
    "guard", "guess", "guide", "guilt", "guitar", "habitat", "hammer", "hamster",
    "harbor", "harsh", "harvest", "hawk", "hazard", "helmet", "hero", "highway",
    "history", "hobby", "hollow", "honey", "hood", "hope", "horn", "horror",
    "hospital", "host", "hover", "humble", "humor", "hundred", "hungry", "hurdle",
    "hurry", "husband", "hybrid", "icon", "idea", "identify", "ignore", "image",
    "imitate", "immense", "immune", "impact", "import", "impose", "improve", "impulse",
    "include", "income", "increase", "index", "indicate", "indoor", "industry", "infant",
    "inflict", "inform", "inhale", "inherit", "initial", "inject", "injury", "inner",
    "innocent", "input", "inquiry", "insane", "insect", "inside", "inspire", "install",
    "intact", "interest", "into", "invest", "invite", "iron", "island", "isolate",
